# Filename: print-stmt-quantile-analysis.Rmd

# About: 
 - This R script is used to debug the outputs from the following:
  - Python script: `print-stmt-quantile-analysis.py`


# Read the CSV file containing all the project scores
```{r echo=TRUE}
library(data.table)
library(dplyr)
library(bit64)

# project_scores <- fread("/Dr. Cliff Shaffer's Lab/DPS Classify and Analysis Oct, 2018/Analysis by Quantile Values Nov 2018/web-cat-all_output_submission_data.csv")

all_print_stmts <- fread("/Dr. Cliff Shaffer's Lab/DPS Classify and Analysis Oct, 2018/print-stmt all versions/Nov 09, 2018/print-stmts.csv")

classified_print_stmts_proj_1 <- fread("/Dr. Cliff Shaffer's Lab/DPS Classify and Analysis Oct, 2018/Analysis by Quantile Values Nov 2018/From_Python_script/Project 1_print_stmt_list.csv")
classified_print_stmts_proj_2 <- fread("/Dr. Cliff Shaffer's Lab/DPS Classify and Analysis Oct, 2018/Analysis by Quantile Values Nov 2018/From_Python_script/Project 2_print_stmt_list.csv")
classified_print_stmts_proj_3 <- fread("/Dr. Cliff Shaffer's Lab/DPS Classify and Analysis Oct, 2018/Analysis by Quantile Values Nov 2018/From_Python_script/Project 3_print_stmt_list.csv")
classified_print_stmts_proj_4 <- fread("/Dr. Cliff Shaffer's Lab/DPS Classify and Analysis Oct, 2018/Analysis by Quantile Values Nov 2018/From_Python_script/Project 4_print_stmt_list.csv")

```

# Separating the data based on Project no

```{r echo=TRUE}
proj_1_print_stmts <- filter(all_print_stmts, all_print_stmts$CASSIGNMENTNAME == "Project 1")
proj_2_print_stmts <- filter(all_print_stmts, all_print_stmts$CASSIGNMENTNAME == "Project 2")
proj_3_print_stmts <- filter(all_print_stmts, all_print_stmts$CASSIGNMENTNAME == "Project 3")
proj_4_print_stmts <- filter(all_print_stmts, all_print_stmts$CASSIGNMENTNAME == "Project 4")
```

# Viewing different variables
```{r echo=TRUE}
specific_project <- filter(all_print_stmts, all_print_stmts$projectId == "1aa1f06c-44a1-484e-931e-cda257938f44")

specific_project <- setDT(specific_project)

specific_project_2 <- filter(classified_print_stmts_proj_2, classified_print_stmts_proj_2$projectId == "0049f7b2-3c13-4da0-9fa2-553b87cbbe71")

specific_project_2 <- setDT(specific_project_2)

View(head(specific_project[order(time),], n=1000))

View(head(specific_project_2[order(time),], n=1000))

View(head(all_print_stmts[order(time),], n=1000))
View(head(classified_print_stmts_proj_1, n=100))
View(head(classified_print_stmts_proj_2, n=100))
```